<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTRJe3DD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTRJe3DD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTRJe3DD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTRJe3DD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTRJe3DD\App_KernelDevDebugContainer([
    'container.build_hash' => 'TRJe3DD',
    'container.build_id' => 'ec426c16',
    'container.build_time' => 1718617762,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTRJe3DD');
