<?php

namespace ContainerBVIhc9V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2VgkM90Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2VgkM90' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2VgkM90'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'enseignant' => ['privates', '.errored..service_locator.2VgkM90.App\\Entity\\Enseignant', NULL, 'Cannot autowire service ".service_locator.2VgkM90": it needs an instance of "App\\Entity\\Enseignant" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'enseignant' => 'App\\Entity\\Enseignant',
            'entityManager' => '?',
            'passwordHasher' => '?',
        ]);
    }
}
