<?php

namespace ContainerBVIhc9V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pm1LmEBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Pm1LmEB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Pm1LmEB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'enseignant' => ['privates', '.errored..service_locator.Pm1LmEB.App\\Entity\\Enseignant', NULL, 'Cannot autowire service ".service_locator.Pm1LmEB": it needs an instance of "App\\Entity\\Enseignant" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'enseignant' => 'App\\Entity\\Enseignant',
            'entityManager' => '?',
        ]);
    }
}
