<?php

namespace ContainerTRJe3DD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserUpdateTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\UserUpdateType' shared autowired service.
     *
     * @return \App\Form\UserUpdateType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/UserUpdateType.php';

        return $container->privates['App\\Form\\UserUpdateType'] = new \App\Form\UserUpdateType();
    }
}
