<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBVIhc9V\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBVIhc9V/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBVIhc9V.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBVIhc9V\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBVIhc9V\App_KernelDevDebugContainer([
    'container.build_hash' => 'BVIhc9V',
    'container.build_id' => 'e2ad79bc',
    'container.build_time' => 1718786447,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBVIhc9V');
