<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'enseignant_list' => [[], ['_controller' => 'App\\Controller\\EnseignantController::list'], [], [['text', '/enseignants']], [], [], []],
    'dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::index'], [], [['text', '/dashboard']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], [], [], [['text', '/logout']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'matiere_add' => [[], ['_controller' => 'App\\Controller\\MatiereController::add'], [], [['text', '/matiere/add']], [], [], []],
    'matiere_list' => [[], ['_controller' => 'App\\Controller\\MatiereController::list'], [], [['text', '/matieres']], [], [], []],
    'enseignant_edit' => [['id'], ['_controller' => 'App\\Controller\\EnseignantController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/enseignant']], [], [], []],
    'enseignant_delete' => [['id'], ['_controller' => 'App\\Controller\\EnseignantController::delete'], [], [['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'matiere_edit' => [['id'], ['_controller' => 'App\\Controller\\MatiereController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/matiere']], [], [], []],
    'matiere_delete' => [['id'], ['_controller' => 'App\\Controller\\MatiereController::delete'], [], [['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'enseignant_add_matiere' => [[], ['_controller' => 'App\\Controller\\EnseignantController::addMatiere'], [], [['text', '/enseignant/add-matiere']], [], [], []],
];
